--- #YAML:1.0
name:                PerlIO-Util
version:             0.51
abstract:            A selection of general PerlIO utilities
license:             perl
author:              
    - Goro Fuji <gfuji (at) cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
