---
abstract: 'A selection of general PerlIO utilities'
author:
  - 'Goro Fuji (藤 吾郎) <gfuji(at)cpan.org>'
configure_requires:
  ExtUtils::MakeMaker: 6.44
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PerlIO-Util
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.60
